### ISSUE TITLE
关于编译时的目录结构

### ISSUE THREAD

**Issue by inkydragon** [Becavalier/Cinderella#2]
Readme 里没写什么时候 clone repo，也没写 llvm 改放到哪。

我自己试了一下都放到 home 目录下，编译完 llvm 然后再去 cmake repo 就报错。看了一眼

https://github.com/Becavalier/Cinderella/blob/a09f4320b04de75c68815a8bab97d138f0ac233c/CMakeLists.txt#L8

感觉应该是 repo 随你放到哪，llvm 源码解压到 repo 里，然后编译 llvm，再编译 repo。

我都放到根目录下了，弄了个符号链接，也可以用
```
~
├── Cinderella
│   ├── llvm -> ~/llvm/
│   └ ...
└─── llvm
```

所以应该再 ReadMe 的 1~4 前加个 
0. clone repo
  `git clone https://github.com/Becavalier/Cinderella.git`
  `cd Cinderella`

然后再进行后续操作

----

不知道我理解的对不对。
我反正是编译成功了。

另：第二步的 `make install` 会复制东西到 `/usr/local/bin/` 得加上 `sudo` 才能成功

**Comment by inkydragon** [comment]
今天突然发现硬盘爆满。一看 llvm/build 23G ..., 编译完的 bin 13.5G。真的大

llvm 的文档也说是差不多这么大
> An LLVM-only build will need about 1-3 GB of space. A full build of LLVM and Clang will need around 15-20 GB of disk space. 

可以再限制一下支持的平台 `LLVM_TARGETS_TO_BUILD` 并指定编译的类型 `CMAKE_BUILD_TYPE` 
- [Getting Started with the LLVM System — LLVM 9 documentation](https://llvm.org/docs/GettingStarted.html#local-llvm-configuration)

翻了下文档，按默认配置编译出的是 debug 版、未优化、带断言。
可以考虑换成优化过+去掉断言的 Release 或者 RelWithDebInfo 版。

> `-DCMAKE_BUILD_TYPE=[Debug|Release|RelWithDebInfo]`
> —— [Getting Started with the LLVM System — LLVM 9 documentation](https://llvm.org/docs/GettingStarted.html#compiling-the-llvm-suite-source-code)

这样应该就小很多了，还会快一点。

**Comment by inkydragon** [comment]
```sh
cmake -G "Unix Makefiles" \
-DCMAKE_C_COMPILER=/usr/bin/clang \
-DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
-DCMAKE_BUILD_TYPE=Release \
-DLLVM_TARGETS_TO_BUILD=host \
..
```

这样编译 llvm，整个 llvm 文件夹占用就只有 1G 了。

后面再
```
cd ../..
pwd
# ~/Cinderella
cd build && cmake -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly ..
make -j 2 
sudo make install
```
后面都一切顺利
整套弄完，Cinderella 文件夹内（源码+编译产生的文件，含 llvm）占用 1.1 G。
LLVM 还是大头，应该还能继续去除不用的组件，减小体积。

**Comment by Becavalier** [comment]
@inkydragon Thank you so much!! Yes, you are right. I will revise the doc during the festival asap. : )
